### PR TITLE
fix the period init

### PR DESCRIPTION
**Pull request by Ganariya**
fix the period init in plugins , periodreset, pheromoneflip

### CODE REVIEW

**Comment by rhgrant10** [comment]
Hi @Ganariya, thanks for contributing. Can you help me understand the problem your change addresses?

**Comment by Ganariya** [comment]
Hello, @rhgrant10 .
Thank you for replying my pull request.

In [PeriodicActionPlugins](https://github.com/rhgrant10/acopy/blob/70554fe63f8beb231256dae553de22bccf911baf/acopy/plugins.py#L44)
, this class has SolverPlugin and __init__ has period settings.

But, [PeriodicReset])(https://github.com/rhgrant10/acopy/blob/70554fe63f8beb231256dae553de22bccf911baf/acopy/plugins.py#L63)
and [PeriodicFlip](https://github.com/rhgrant10/acopy/blob/70554fe63f8beb231256dae553de22bccf911baf/acopy/plugins.py#L70)
do not have __init__ and cannot set period in constructor.

So, this pull requests adds the constructor

```python
    def __init__(self, period=50):
        super().__init__(period=period)
```

only.

**Comment by rhgrant10** [comment]
I see. It's actually not needed because when a method is not found on an object Python looks to the parent object for a definition. For example:

```python
class Example:
    def __init__(self, value=42):
        self.value = value

class Example2(Example):
    pass  # all methods inherited from Example

# both of these result in calls to Example.__init__
e1 = Example2()
e2 = Example2(value=100)

# and as you would expect:
assert e1.value == 42
assert e2.value == 100
```
The `period` parameter can be set on these subclasses without issue:
```python
>>> import acopy
>>> acopy.plugins.PeriodicReset?
Init signature: acopy.plugins.PeriodicReset(period=50)
Docstring:
Solver plugin.

Solver plugins can be added to any solver to customize its behavior.
Plugins are initilized once when added, once before the first solver
iteration, once after each solver iteration has completed, and once after
all iterations have completed.

Implenting each hook is optional.
File:           ~/code/acopy/acopy/plugins.py
Type:           type
Subclasses:
>>> p = acopy.plugins.PeriodicReset(period=100)
>>> p.period
100
```

**Comment by Ganariya** [comment]
@rhgrant10 
Thank you for reply!

I do not know the python's constructor in __init__.
and I came to know the behaviour of the inheritance init now.

Thank you! I grow up again now.
I close this issue (><)

**Pull request closed without merging**
